### ISSUE TITLE
please help with version `libcrypto.so.10' not found

### ISSUE THREAD

**Issue by nguyenxuanlamiwe** [bakatrouble/pytgvoip#1]
Traceback (most recent call last):
  File "/home/osboxes/PycharmProjects/voiceapi/app/appvoice.py", line 2, in <module>
    from tgvoip_pyrogram import VoIPFileStreamService
  File "/home/osboxes/PycharmProjects/voiceapi/venv/lib/python3.5/site-packages/tgvoip_pyrogram/__init__.py", line 19, in <module>
    from tgvoip_pyrogram.service import VoIPService
  File "/home/osboxes/PycharmProjects/voiceapi/venv/lib/python3.5/site-packages/tgvoip_pyrogram/service.py", line 25, in <module>
    from tgvoip_pyrogram.incoming_call import VoIPIncomingCall
  File "/home/osboxes/PycharmProjects/voiceapi/venv/lib/python3.5/site-packages/tgvoip_pyrogram/incoming_call.py", line 26, in <module>
    from tgvoip import CallState
  File "/home/osboxes/PycharmProjects/voiceapi/venv/lib/python3.5/site-packages/tgvoip/__init__.py", line 20, in <module>
    from tgvoip.tgvoip import *
  File "/home/osboxes/PycharmProjects/voiceapi/venv/lib/python3.5/site-packages/tgvoip/tgvoip.py", line 26, in <module>
    from _tgvoip import (
ImportError: /home/osboxes/PycharmProjects/voiceapi/venv/lib/python3.5/site-packages/.libs_tgvoip/libcrypto-a94305d7.so.1.0.1e: version `libcrypto.so.10' not found (required by /home/osboxes/PycharmProjects/voiceapi/venv/lib/python3.5/site-packages/.libs_tgvoip/libtgvoip-d66a5fc7.so.0.0.0)

Process finished with exit code 1

**Comment by bakatrouble** [comment]
It's an issue with `auditwheel`: https://github.com/pypa/auditwheel/issues/159, for the time being this library could be installed from source

libtgvoip building instructions are available here: https://pytgvoip.readthedocs.io/en/latest/guides/libtgvoip.html

Make sure that you have CMake installed, and then install pytgvoip using pip with `--no-binary flag`

**Comment by bakatrouble** [comment]
This issue is connected with broken wheels for linux, they are removed from pypi now
