### ISSUE TITLE
Error comes up when installing

### ISSUE THREAD

**Issue by ShapedTime** [bakatrouble/pytgvoip#4]
## How to generate the issue:
`pip3 install pytgvoip`
## What happens:
```
Collecting pytgvoip
  Using cached https://files.pythonhosted.org/packages/ee/6b/07f67f9904d7f697084d7a3577a773760a366b90ed248ed5542037b45191/pytgvoip-0.0.2.7.tar.gz
Building wheels for collected packages: pytgvoip
  Building wheel for pytgvoip (setup.py) ... error
  ERROR: Complete output from command /usr/local/opt/python/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-wheel-fxkupjxp --python-tag cp37:
  ERROR: /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'python_required'
    warnings.warn(msg)
  /usr/local/lib/python3.7/site-packages/setuptools/dist.py:481: UserWarning: The version specified ('0.0.2.7.develop') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
    "details." % self.metadata.version
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.14-x86_64-3.7
  creating build/lib.macosx-10.14-x86_64-3.7/tgvoip
  copying src/tgvoip/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/tgvoip
  copying src/tgvoip/utils.py -> build/lib.macosx-10.14-x86_64-3.7/tgvoip
  copying src/tgvoip/tgvoip.py -> build/lib.macosx-10.14-x86_64-3.7/tgvoip
  running build_ext
  -- The C compiler identification is AppleClang 10.0.1.10010046
  -- The CXX compiler identification is AppleClang 10.0.1.10010046
  -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
  -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
  -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- TGVOIP_INCLUDE_DIR-NOTFOUND
  -- TGVOIP_LIBRARY-NOTFOUND
  -- Could NOT find TGVOIP (missing: TGVOIP_INCLUDE_DIR TGVOIP_LIBRARY)
  -- Found PythonInterp: /usr/local/opt/python/bin/python3.7 (found version "3.7.4")
  -- Found PythonLibs: /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib
  -- pybind11 v2.3.dev0
  -- Performing Test HAS_FLTO
  -- Performing Test HAS_FLTO - Success
  -- LTO enabled
  CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
  Please set them or make sure they are set and tested correctly in the CMake files:
  TGVOIP_INCLUDE_DIR (ADVANCED)
     used as include directory in directory /private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip
     used as include directory in directory /private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip
     used as include directory in directory /private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip
  TGVOIP_LIBRARY (ADVANCED)
      linked by target "_tgvoip" in directory /private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip

  -- Configuring incomplete, errors occurred!
  See also "/private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip/build/temp.macosx-10.14-x86_64-3.7/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip/setup.py", line 161, in <module>
      'Topic :: Software Development :: Libraries :: Python Modules',
    File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip/setup.py", line 69, in run
      self.build_extension(ext)
    File "/private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip/setup.py", line 93, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
    File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip/build/lib.macosx-10.14-x86_64-3.7', '-DPYTHON_EXECUTABLE=/usr/local/opt/python/bin/python3.7', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for pytgvoip
  Running setup.py clean for pytgvoip
Failed to build pytgvoip
Installing collected packages: pytgvoip
  Running setup.py install for pytgvoip ... error
    ERROR: Complete output from command /usr/local/opt/python/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-record-9iluv1wc/install-record.txt --single-version-externally-managed --compile:
    ERROR: /usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'python_required'
      warnings.warn(msg)
    /usr/local/lib/python3.7/site-packages/setuptools/dist.py:481: UserWarning: The version specified ('0.0.2.7.develop') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
      "details." % self.metadata.version
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.14-x86_64-3.7
    creating build/lib.macosx-10.14-x86_64-3.7/tgvoip
    copying src/tgvoip/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/tgvoip
    copying src/tgvoip/utils.py -> build/lib.macosx-10.14-x86_64-3.7/tgvoip
    copying src/tgvoip/tgvoip.py -> build/lib.macosx-10.14-x86_64-3.7/tgvoip
    running build_ext
    -- The C compiler identification is AppleClang 10.0.1.10010046
    -- The CXX compiler identification is AppleClang 10.0.1.10010046
    -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
    -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
    -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- TGVOIP_INCLUDE_DIR-NOTFOUND
    -- TGVOIP_LIBRARY-NOTFOUND
    -- Could NOT find TGVOIP (missing: TGVOIP_INCLUDE_DIR TGVOIP_LIBRARY)
    -- Found PythonInterp: /usr/local/opt/python/bin/python3.7 (found version "3.7.4")
    -- Found PythonLibs: /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib
    -- pybind11 v2.3.dev0
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- LTO enabled
    CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
    Please set them or make sure they are set and tested correctly in the CMake files:
    TGVOIP_INCLUDE_DIR (ADVANCED)
       used as include directory in directory /private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip
       used as include directory in directory /private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip
       used as include directory in directory /private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip
    TGVOIP_LIBRARY (ADVANCED)
        linked by target "_tgvoip" in directory /private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip

    -- Configuring incomplete, errors occurred!
    See also "/private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip/build/temp.macosx-10.14-x86_64-3.7/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip/setup.py", line 161, in <module>
        'Topic :: Software Development :: Libraries :: Python Modules',
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip/setup.py", line 69, in run
        self.build_extension(ext)
      File "/private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip/setup.py", line 93, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
      File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip/build/lib.macosx-10.14-x86_64-3.7', '-DPYTHON_EXECUTABLE=/usr/local/opt/python/bin/python3.7', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command "/usr/local/opt/python/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-record-9iluv1wc/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/_r/zy42qp913_z34sr_fkkp8yzw0000gq/T/pip-install-db6j6tjf/pytgvoip/
```
## What's actually expected to happen:
It should be installed.
## My system information:

- `python --version` : Python 2.7.10
- `python3 --version` : Python 3.7.4
- Macbook Pro Mid 2014
- Mojave version 10.14.6

**Comment by chuabingquan** [comment]
@TeymurPC Did you manage to resolve this? I'm having a similar issue too on my MacBook Pro.

**Comment by bakatrouble** [comment]
This error means that dynamically linked libtgvoip was not found
libtgvoip is now built during installation and linked statically
